server:
  port: 8081

spring:
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST}
      port: ${SPRING_CLOUD_CONSUL_PORT}
      discovery:
        prefer-ip-address: true
        service-name: SERVICE-CLIENT
  application:
    name: SERVICE-CLIENT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysql:3306/clientservicedb?createDatabaseIfNotExist=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true